version: '3'

env:
  GOOS: "{{OS}}"

vars:
  TEST_DB_URL: "postgres://postgres:postgres@127.0.0.1:5432/tlz?sslmode=disable"
  LOCAL_HOST: 127.0.0.1

tasks:
  test:
    cmds:
      - go test ./...

  build:
    cmds:
      - task: build:{{OS}}

  build:windows:
    cmds:
      - go env -w GOOS=windows GOARCH=amd64
      - go build -o bin/server.exe ./cmd/server/main.go

  build:darwin:
    cmds:
      - go env -w GOOS=darwin GOARCH=amd64
      - go build -o bin/server ./cmd/server/main.go

  build:linux:
    cmds:
      - go env -w GOOS=linux GOARCH=amd64
      - go build -o bin/server ./cmd/server/main.go

  run:
    cmds:
      - task: build:{{OS}}
      - task: run:{{OS}}
        vars:
          ARGS: "{{.CLI_ARGS}}"

  run:darwin:
    cmds:
      - bin/server {{.ARGS}}
  run:linux:
    cmds:
      - bin/server {{.ARGS}}
  run:windows:
    cmds:
      - bin/server.exe {{.ARGS}}

  lint:
    cmds:
      - golangci-lint run ./... -v --timeout 5m

  scan:
    cmds:
      - gosec -conf .gosec.config.json "./..."

  tools:install:
    desc: Install tools
    cmds:
      - task tools:install:golangci-lint
      - task tools:install:gosec

  tools:install:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tools:install:gosec:
    desc: Install gosec
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest

