version: '3'

includes:
  bootstrap_tasks: .taskfiles/bootstrap.yaml
  container_tasks: .taskfiles/containers.yaml
  build_tasks: .taskfiles/build.yaml
  test_tasks: .taskfiles/test.yaml
  gen_tasks: .taskfiles/gen.yaml

env:
  GOOS: "{{OS}}"

vars:
  TEST_DB_URL: "postgres://postgres:postgres@127.0.0.1:5432/tlz?sslmode=disable"
  LOCAL_HOST: 127.0.0.1

tasks:

  ################################################################
  # Bootstrap tasks
  ################################################################
  bootstrap:
    desc: Install all necessary tools and CLI dependencies
    cmds:
      - task: bootstrap_tasks:local

  boostrap:gh:
    desc: Install all necessary tools and CLI dependencies for GitHub Actions
    cmds:
      - task: bootstrap_tasks:gh


  ################################################################
  # Build tasks
  ################################################################
  build:
    cmds:
      - task: build_tasks:build

  build:pack:
    cmds:
      - task: build_tasks:build:pack

  build:pack:gh:
    cmds:
      - task: build_tasks:build:pack:gh

  ################################################################
  # Test tasks
  ################################################################
  lint:
    cmds:
      - task: test_tasks:lint

  scan:
    cmds:
      - task: test_tasks:scan

  test:
    cmds:
      - task: test_tasks:test

  run:
    cmds:
      - task: test_tasks:run

  preview:
    cmds:
      - task: test_tasks:preview

  evans:
    cmds:
      - task: test_tasks:evans

  ################################################################
  # Generate tasks
  ################################################################
  proto:
    cmds:
      - task: gen_tasks:proto

  mock:
    cmds:
      - task: gen_tasks:mock

  sqlc:
    cmds:
      - task: gen_tasks:sqlc


  ################################################################
  # Container tasks
  ################################################################
  pg:
    cmds:
      - task: container_tasks:pg

  pg:start:
    cmds:
      - task: container_tasks:pg:start

  pg:down:
    cmds:
      - task: container_tasks:pg:down

  redis:
    cmds:
      - task: container_tasks:redis

  redis:start:
    cmds:
      - task: container_tasks:redis:start

  redis:down:
    cmds:
      - task: container_tasks:redis:down

  mailhog:
    cmds:
      - task: container_tasks:mailhog

  mailhog:start:
    cmds:
      - task: container_tasks:mailhog:start

  mailhog:down:
    cmds:
      - task: container_tasks:mailhog:down
