// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: domain.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE name = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteDomain, name)
	return err
}

const getAllDomains = `-- name: GetAllDomains :many
SELECT id, name, certificate_expiry, status, issuer, owner, created_at FROM domains
ORDER BY name
`

func (q *Queries) GetAllDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CertificateExpiry,
			&i.Status,
			&i.Issuer,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDomainsByOwner = `-- name: GetAllDomainsByOwner :many
SELECT id, name, certificate_expiry, status, issuer, owner, created_at FROM domains
WHERE owner = $1
ORDER BY name
`

func (q *Queries) GetAllDomainsByOwner(ctx context.Context, owner uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getAllDomainsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CertificateExpiry,
			&i.Status,
			&i.Issuer,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomain = `-- name: GetDomain :one
SELECT id, name, certificate_expiry, status, issuer, owner, created_at FROM domains WHERE name = $1
`

func (q *Queries) GetDomain(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByOwner = `-- name: GetDomainByOwner :one
SELECT id, name, certificate_expiry, status, issuer, owner, created_at FROM domains
WHERE owner = $1 AND name = $2
`

type GetDomainByOwnerParams struct {
	Owner uuid.UUID `json:"owner"`
	Name  string    `json:"name"`
}

func (q *Queries) GetDomainByOwner(ctx context.Context, arg GetDomainByOwnerParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByOwner, arg.Owner, arg.Name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const insertDomain = `-- name: InsertDomain :one
INSERT INTO domains
    (name,status)
VALUES ($1,$2)
RETURNING id, name, certificate_expiry, status, issuer, owner, created_at
`

type InsertDomainParams struct {
	Name   string      `json:"name"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) InsertDomain(ctx context.Context, arg InsertDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, insertDomain, arg.Name, arg.Status)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const updateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET status = $1, certificate_expiry = $2, issuer = $3
WHERE name = $4
RETURNING id, name, certificate_expiry, status, issuer, owner, created_at
`

type UpdateDomainParams struct {
	Status            pgtype.Text      `json:"status"`
	CertificateExpiry pgtype.Timestamp `json:"certificate_expiry"`
	Issuer            pgtype.Text      `json:"issuer"`
	Name              string           `json:"name"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomain,
		arg.Status,
		arg.CertificateExpiry,
		arg.Issuer,
		arg.Name,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}
