// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Domain struct {
	Name              string         `json:"name"`
	CertificateExpiry sql.NullTime   `json:"certificate_expiry"`
	Status            sql.NullString `json:"status"`
	Issuer            sql.NullString `json:"issuer"`
}

type Notification struct {
	ID        int32     `json:"id"`
	Subject   string    `json:"subject"`
	Message   string    `json:"message"`
	SendTo    string    `json:"send_to"`
	Channel   string    `json:"channel"`
	CreatedAt time.Time `json:"created_at"`
}
