// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Domain struct {
	ID                uuid.UUID        `json:"id"`
	Name              string           `json:"name"`
	CertificateExpiry pgtype.Timestamp `json:"certificate_expiry"`
	Status            pgtype.Text      `json:"status"`
	Issuer            pgtype.Text      `json:"issuer"`
	Owner             uuid.UUID        `json:"owner"`
	CreatedAt         time.Time        `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID `json:"id"`
	Subject   string    `json:"subject"`
	Message   string    `json:"message"`
	SendTo    string    `json:"send_to"`
	Channel   string    `json:"channel"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
