// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Domain struct {
	Name              string         `json:"name"`
	CertificateExpiry sql.NullTime   `json:"certificate_expiry"`
	Status            sql.NullString `json:"status"`
	Issuer            sql.NullString `json:"issuer"`
}
