// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: notifications.sql

package db

import (
	"context"
)

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, message, send_to, channel, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.SendTo,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const getNotifications = `-- name: GetNotifications :many
SELECT id, message, send_to, channel, created_at FROM notifications
`

func (q *Queries) GetNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.SendTo,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByChannel = `-- name: GetNotificationsByChannel :many
SELECT id, message, send_to, channel, created_at FROM notifications WHERE channel = $1
`

func (q *Queries) GetNotificationsByChannel(ctx context.Context, channel string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.SendTo,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications
  (message, send_to, channel)
VALUES ($1, $2, $3)
RETURNING id, message, send_to, channel, created_at
`

type InsertNotificationParams struct {
	Message string `json:"message"`
	SendTo  string `json:"send_to"`
	Channel string `json:"channel"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification, arg.Message, arg.SendTo, arg.Channel)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.SendTo,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const updateNotification = `-- name: UpdateNotification :one
UPDATE notifications SET message = $1, send_to = $2, channel = $3
WHERE id = $4
RETURNING id, message, send_to, channel, created_at
`

type UpdateNotificationParams struct {
	Message string `json:"message"`
	SendTo  string `json:"send_to"`
	Channel string `json:"channel"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotification,
		arg.Message,
		arg.SendTo,
		arg.Channel,
		arg.ID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.SendTo,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}
