// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	DeleteDomain(ctx context.Context, name string) error
	GetDomain(ctx context.Context, name string) (Domain, error)
	GetDomains(ctx context.Context) ([]Domain, error)
	InsertDomain(ctx context.Context, arg InsertDomainParams) (Domain, error)
	UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error)
}

var _ Querier = (*Queries)(nil)
