// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDomain(ctx context.Context, name string) error
	DeleteNotification(ctx context.Context, id int32) error
	GetDomain(ctx context.Context, name string) (Domain, error)
	GetDomains(ctx context.Context) ([]Domain, error)
	GetNotification(ctx context.Context, id int32) (Notification, error)
	GetNotifications(ctx context.Context) ([]Notification, error)
	GetNotificationsByChannel(ctx context.Context, channel string) ([]Notification, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	InsertDomain(ctx context.Context, arg InsertDomainParams) (Domain, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error)
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (Notification, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
