// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: domain.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE name = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteDomain, name)
	return err
}

const getAllDomains = `-- name: GetAllDomains :many
SELECT id, name, certificate_expiry, status, issuer, created_at, namespace FROM domains
ORDER BY name
`

func (q *Queries) GetAllDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CertificateExpiry,
			&i.Status,
			&i.Issuer,
			&i.CreatedAt,
			&i.Namespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDomainsByNamespace = `-- name: GetAllDomainsByNamespace :many
SELECT id, name, certificate_expiry, status, issuer, created_at, namespace FROM domains
WHERE namespace = $1
ORDER BY name
`

func (q *Queries) GetAllDomainsByNamespace(ctx context.Context, namespace uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getAllDomainsByNamespace, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CertificateExpiry,
			&i.Status,
			&i.Issuer,
			&i.CreatedAt,
			&i.Namespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomain = `-- name: GetDomain :one
SELECT id, name, certificate_expiry, status, issuer, created_at, namespace FROM domains WHERE name = $1
`

func (q *Queries) GetDomain(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.CreatedAt,
		&i.Namespace,
	)
	return i, err
}

const getDomainByNamespace = `-- name: GetDomainByNamespace :one
SELECT id, name, certificate_expiry, status, issuer, created_at, namespace FROM domains
WHERE namespace = $1 AND name = $2
`

type GetDomainByNamespaceParams struct {
	Namespace uuid.UUID `json:"namespace"`
	Name      string    `json:"name"`
}

func (q *Queries) GetDomainByNamespace(ctx context.Context, arg GetDomainByNamespaceParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByNamespace, arg.Namespace, arg.Name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.CreatedAt,
		&i.Namespace,
	)
	return i, err
}

const insertDomain = `-- name: InsertDomain :one
INSERT INTO domains
    (name,status,namespace)
VALUES ($1,$2,$3)
RETURNING id, name, certificate_expiry, status, issuer, created_at, namespace
`

type InsertDomainParams struct {
	Name      string      `json:"name"`
	Status    pgtype.Text `json:"status"`
	Namespace uuid.UUID   `json:"namespace"`
}

func (q *Queries) InsertDomain(ctx context.Context, arg InsertDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, insertDomain, arg.Name, arg.Status, arg.Namespace)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.CreatedAt,
		&i.Namespace,
	)
	return i, err
}

const updateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET status = $1, certificate_expiry = $2, issuer = $3
WHERE name = $4
RETURNING id, name, certificate_expiry, status, issuer, created_at, namespace
`

type UpdateDomainParams struct {
	Status            pgtype.Text      `json:"status"`
	CertificateExpiry pgtype.Timestamp `json:"certificate_expiry"`
	Issuer            pgtype.Text      `json:"issuer"`
	Name              string           `json:"name"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomain,
		arg.Status,
		arg.CertificateExpiry,
		arg.Issuer,
		arg.Name,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertificateExpiry,
		&i.Status,
		&i.Issuer,
		&i.CreatedAt,
		&i.Namespace,
	)
	return i, err
}
