// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Domain struct {
	ID                uuid.UUID        `json:"id"`
	Name              string           `json:"name"`
	CertificateExpiry pgtype.Timestamp `json:"certificate_expiry"`
	Status            pgtype.Text      `json:"status"`
	Issuer            pgtype.Text      `json:"issuer"`
	CreatedAt         time.Time        `json:"created_at"`
	Namespace         uuid.UUID        `json:"namespace"`
}

type Namespace struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Enabled           bool               `json:"enabled"`
	BillingEnabled    bool               `json:"billing_enabled"`
	BillingPeriod     string             `json:"billing_period"`
	BillingPrice      int32              `json:"billing_price"`
	BillingCurrency   string             `json:"billing_currency"`
	BillingLastCharge pgtype.Timestamptz `json:"billing_last_charge"`
	BillingNextCharge pgtype.Timestamptz `json:"billing_next_charge"`
	Owner             uuid.UUID          `json:"owner"`
	CreatedAt         time.Time          `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID `json:"id"`
	Subject   string    `json:"subject"`
	Message   string    `json:"message"`
	SendTo    string    `json:"send_to"`
	Channel   string    `json:"channel"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	IsEmailVerified   bool      `json:"is_email_verified"`
}

type VerifyEmail struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
