name: lint

defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths-ignore:
      - '*.http'
      - 'README.md'
      - 'docs/**'
      - '.github/**'
      - 'scripts/**'
      - 'LICENSE'
      - 'sqlc.yaml'
      - 'Taskfile.yaml'
      - '.gitignore'
      - 'project.toml'
      - '.gosec.config.json'
      - '.editorconfig'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          stable: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 60s --max-same-issues 50
