name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths-ignore:
      - '*.http'
      - 'README.md'
      - 'docs/**'
      - '.github/**'
      - '.taskfiles/**'
      - 'scripts/**'
      - 'LICENSE'
      - 'sqlc.yaml'
      - 'Taskfile.yaml'
      - '.gitignore'
      - 'project.toml'
      - '.gosec.config.json'
      - '.editorconfig'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.20'

      - name: Install Task
        uses: arduino/setup-task@v1.0.3
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Linter
        run: task bootstrap_tasks:install:golangci-lint

      - name: Lint
        run: task lint
