name: Release

# This ensures that the release is only created after the Docker Build Pipeline
# has successfully completed.
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:

  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    # This if condition checks two things:
    # 1. That the Build pipeline completed successfully.
    # 2. That the current ref is a tag.
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
