name: test

on:
  push:
    tags:
    branches:
    paths-ignore:
      - '*.http'
      - 'README.md'
      - 'docs/**'
      - '.github/**'
      - 'scripts/**'
      - 'LICENSE'
      - 'sqlc.yaml'
      - 'Taskfile.yaml'
      - '.gitignore'
      - 'project.toml'
      - '.gosec.config.json'
      - '.editorconfig'
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tlz
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
        options: --health-cmd wget -T 10 -s http://localhost:8025 || exit 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          stable: true

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: task test
