name: test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths-ignore:
      - '*.http'
      - 'README.md'
      - 'docs/**'
      - '.github/**'
      - 'scripts/**'
      - 'LICENSE'
      - 'sqlc.yaml'
      - 'Taskfile.yaml'
      - '.gitignore'
      - 'project.toml'
      - '.gosec.config.json'
      - '.editorconfig'

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tlz
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          stable: false

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build web
        run: task react:build

      - name: Install golangci-lint
        run: task install:golangci-lint

      - name: Lint
        run: task lint

      - name: Test
        run: task test
